<template>
  <SectionPage v-bind="page">
    <section class="article">
      <div class="citation">
        <p>Kazi Sajeed Mehrab, M. Maruf, Arka Daw, Abhilash Neog, Harish Babu Manogaran, Mridul Khurana, Zhenyang Feng, Bahadir Altintas, Yasin Bakis, Elizabeth G Campolongo, Matthew J Thompson, Xiaojun Wang, Hilmar Lapp, Tanya Berger-Wolf, Paula Mabee, Henry Bart, Wei-Lun Chao, Wasila M Dahdul, and Anuj Karpatne (2025). <span class="title">Fish-Vista: A Multi-Purpose Dataset for Understanding &amp; Identification of Traits from Images.</span> IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR) June 2025.</p>
        <a href="https://doi.org/10.1109/CVPR52734.2025.02261" class="doi" target="_blank">DOI: 10.1109/CVPR52734.2025.02261</a>
      </div>

      <div class="citation">
        <p>Meghan A. Balk, John Bradley, M. Maruf, Bahadir Altintas, Yasin Bakis, Henry L. Bart, David Breen, Christopher R. Florian, Jane Greenberg, Anuj Karpatne, Kevin Karnani, Paula Mabee, Joel Pepper, Dom Jebbia, Thibault Tabarin, Xiaojun Wang, Hilmar Lapp (2024). <span class="title">A FAIR and modular image-based workflow for knowledge discovery in the emerging field of Imageomics.</span> Methods in Ecology and Evolution 15(6):1129-1145.</p>
        <a href="https://doi.org/10.1111/2041-210X.14327" class="doi" target="_blank">DOI: 10.1111/2041-210X.14327</a>
      </div>

      <div class="citation">
        <p>Mridul Khurana, Arka Daw, M. Maruf, Josef C. Uyeda, Wasila Dahdul, Caleb Charpentier, Yasin Bakis, Henry L. Bart Jr., Paula M. Mabee, Hilmar Lapp, James P. Balhoff, Wei-Lun Chao, Charles Stewart, Tanya Berger-Wolf, and Anuj Karpatne (2024). <span class="title">Hierarchical Conditioning of Diffusion Models Using Tree-of-Life for Studying Species Evolution.</span> In: Computer Vision – ECCV 2024.</p>
        <a href="https://doi.org/10.1007/978-3-031-73024-5_9" class="doi" target="_blank">DOI: 10.1007/978-3-031-73024-5_9</a>
      </div>

      <div class="citation">
        <p>M. Maruf, Arka Daw, Kazi Sajeed Mehrab, Harish Babu Manogaran, Abhilash Neog, Medha Sawhney, Mridul Khurana, James Balhoff, Yasin Bakis, Bahadir Altintas, Matthew J. Thompson, Elizabeth G. Campolongo, Josef C Uyeda, Hilmar Lapp, Henry L. Bart, Paula Mabee, Yu Su, Wei-Lun Chao, Charles V. Stewart, Tanya Berger-Wolf, Wasila M Dahdul, Anuj Karpatne (2024). <span class="title">VLM4Bio: A Benchmark Dataset to Evaluate Pretrained Vision-Language Models for Trait Discovery from Biological Images.</span></p>
        <a href="https://doi.org/10.48550/arXiv.2408.16176" class="doi" target="_blank">DOI: 10.48550/arXiv.2408.16176</a>
      </div>

      <div class="citation">
        <p>Bahadir Altintas, Yasin Bakis, Xiaojun Wang, Henry Bart (2023). <span class="title">Application of AI-Helped Image Classification of Fish Images: An iDigBio dataset example.</span> Biodiversity Information Science and Standards 7: e112438.</p>
        <a href="https://doi.org/10.3897/biss.7.112438" class="doi" target="_blank">DOI: 10.3897/biss.7.112438</a>
      </div>

      <div class="citation">
        <p>Yasin Bakis, Xiaojun Wang, Bahadir Altintas, Dom Jebbia, Henry Bart Jr (2023). <span class="title">On Image Quality Metadata, FAIR in ML, AI-Readiness and Reproducibility: Fish-AIR example.</span> Biodiversity Information Science and Standards 7: e112178.</p>
        <a href="https://doi.org/10.3897/biss.7.112178" class="doi" target="_blank">DOI: 10.3897/biss.7.112178</a>
      </div>

      <div class="citation">
        <p>Kevin Karnani, Joel Pepper, Yasin Bakis, Xiaojun Wang, Henry Bart Jr, David E. Breen, Jane Greenberg (2022). <span class="title">Computational metadata generation methods for biological specimen image collections.</span> International Journal on Digital Libraries.</p>
        <a href="https://doi.org/10.1007/s00799-022-00342-1" class="doi" target="_blank">DOI: 10.1007/s00799-022-00342-1</a>
      </div>

      <div class="citation">
        <p>Dom Jebbia, Xiaojun Wang, Yasin Bakis, Henry L. Bart Jr., Jane Greenberg (2022). <span class="title">Toward a Flexible Metadata Pipeline for Fish Specimen Images.</span> Proceedings for the 16th Metadata and Semantic Research (MTSR), Springer in Communications in Computer and Information Science.</p>
        <a href="https://arxiv.org/abs/2211.15472" class="doi" target="_blank">arxiv.org/abs/2211.15472</a>
      </div>

      <div class="citation">
        <p>Yasin Bakis, Bahadir Altintas, Xiaojun Wang, Moniruzzaman Maruf, Anuj Karpatne, Henry Bart (2022). <span class="title">Extracting Landmark and Trait Information from Segmented Digital Specimen Images Generated by Artificial Neural Networks.</span> Biodiversity Information Science and Standards 6.</p>
        <a href="https://doi.org/10.3897/biss.6.94955" class="doi" target="_blank">DOI: 10.3897/biss.6.94955</a>
      </div>

      <div class="citation">
        <p>Mohannad Elhamod, Kelly M. Diamond, A. Murat Maga, Yasin Bakis, Henry L. Bart Jr., Paula Mabee, Wasila Dahdul, Jeremy Leipzig, Jane Greenberg, Brian Avants, Anuj Karpatne (2021). <span class="title">Hierarchy-guided Neural Networks for Species Classification.</span> Methods in Ecology and Evolution.</p>
        <a href="https://doi.org/10.1111/2041-210X.13768" class="doi" target="_blank">DOI: 10.1111/2041-210X.13768</a>
      </div>

      <div class="citation">
        <p>Joel Pepper, Jane Greenberg, Yasin Bakis, Xiaojun Wang, Henry L Bart, David E Breen (2021). <span class="title">Automatic Metadata Generation for Fish Specimen Image Collections.</span> 2021 ACM/IEEE Joint Conference on Digital Libraries (JCDL). <strong>BEST STUDENT PAPER AWARD</strong></p>
        <a href="https://doi.org/10.1109/JCDL52503.2021.00015" class="doi" target="_blank">DOI: 10.1109/JCDL52503.2021.00015</a>
      </div>

      <div class="citation">
        <p>Jeremy Leipzig, Yasin Bakis, Xiaojun Wang, Mohannad Elhamod, Kelly Diamond, Wasila Dahdul, Anuj Karpatne, Murat Maga, Paula Mabee, Henry L. Bart Jr. &amp; Jane Greenberg (2021). <span class="title">Biodiversity Image Quality Metadata Augments Convolutional Neural Network Classification of Fish Species.</span> In: Metadata and Semantic Research.</p>
        <a href="https://doi.org/10.1007/978-3-030-71903-6_1" class="doi" target="_blank">DOI: 10.1007/978-3-030-71903-6_1</a>
      </div>

      <div class="citation">
        <p>Yasin Bakis, Xiaojun Wang, Hank Bart (2021). <span class="title">Challenges in Curating 2D Multimedia Data in the Application of Machine Learning in Biodiversity Image Analysis.</span> Biodiversity Information Science and Standards 5: e75856.</p>
        <a href="https://doi.org/10.3897/biss.5.75856" class="doi" target="_blank">DOI: 10.3897/biss.5.75856</a>
      </div>

      <div class="citation">
        <p>Yasin Bakis, Xiaojun Wang, Hank Bart (2021). <span class="title">Evaluating the image quality of digitized biodiversity collections' specimens.</span> 5th Annual Digital Data Conference, Florida Museum of Natural History.</p>
      </div>

      <div class="citation">
        <p>Leipzig J, Bakis Y, Wang X, Elhamod M, Diamond K, Maga M, Dahdul W, Karpatne A, Mabee P, Bart Jr H L. and Greenberg J (2020). <span class="title">Biodiversity image quality metadata augments convolutional neural network classification of fish species.</span> 14th International Conference on Metadata and Semantics Research (MTSR 2020), Madrid, Spain. <strong>BEST RESEARCH PAPER AWARD</strong></p>
      </div>

      <div class="citation">
        <p>Hank Bart, Jane Greenberg, Anuj Karpatne, Paula Mabee, A. Murat Maga, Mohannad Elhamod, Abdullah Al Maruf, Prathamesh Mandke, Jeremy Leipzig, Joel Pepper, Yasin Bakis, Brian Avants, Kelly Diamond, Wasila Dahdul, Jim Balhoff, Chris Florian (2021). <span class="title">Biology-guided neural networks (BGNN) for discovering phenotypic traits.</span> Society for Integrative and Comparative Biology (SICB) 2021 Virtual.</p>
      </div>
    </section>
  </SectionPage>
</template>

<script setup>
import SectionPage from '@/components/layout/SectionPage.vue'
import { informaticsSidebar, heroImages } from '@/config/sidebars'

const page = {
  heroImage: heroImages.informatics,
  heroTitle: 'Biodiversity Informatics',
  pageTitle: 'Publications',
  sidebar: informaticsSidebar,
}
</script>

<style scoped>
.citation {
  padding: 18px 0;
  border-bottom: 1px solid var(--c-border);
}
.citation:first-of-type { border-top: 1px solid var(--c-border); }
.citation p {
  font-size: 14px;
  line-height: 1.7;
  color: var(--c-text-secondary);
  margin-bottom: 0;
}
.citation .title { font-weight: 600; font-style: italic; }
.citation .doi {
  display: inline-block; margin-top: 4px;
  font-size: 13px; color: var(--c-accent); word-break: break-all;
}
</style>